import { and, asc, eq, gte, isNull, lt, sql } from "drizzle-orm";
import { calculateBudget, categoryId, createBudget, householdId, money } from "@nodvis/finance-domain";
import { getDb } from "../client";
import { budgets } from "../schema/budgets";
import { categories } from "../schema/categories";
import { transactions } from "../schema/transactions";
export class BudgetNotFoundError extends Error {}
export class BudgetConflictError extends Error {}
export type BudgetSummary = { id:string; householdId:string; categoryId:string; categoryName:string; month:string; limitAmountMinor:bigint; spentAmountMinor:bigint; remainingAmountMinor:bigint; isOverBudget:boolean; currency:string; archivedAt:Date|null; version:number };
function bounds(month:string){const [y,m]=month.split("-").map(Number);return {start:new Date(Date.UTC(y!,m!-1,1)),next:new Date(Date.UTC(y!,m!,1))};}
async function mapRow(row:typeof budgets.$inferSelect, categoryName:string):Promise<BudgetSummary>{const b=bounds(row.month.slice(0,7));const [s]=await getDb().select({value:sql<string>`coalesce(sum(${transactions.amountMinor}), 0)`}).from(transactions).where(and(eq(transactions.householdId,row.householdId),eq(transactions.categoryId,row.categoryId),eq(transactions.currency,row.currency),eq(transactions.kind,"expense"),isNull(transactions.voidedAt),gte(transactions.occurredOn,b.start),lt(transactions.occurredOn,b.next)));const calc=calculateBudget(money(row.limitAmountMinor,row.currency),money(BigInt(s?.value??"0"),row.currency));return {id:row.id,householdId:row.householdId,categoryId:row.categoryId,categoryName,month:row.month.slice(0,7),limitAmountMinor:calc.limitAmountMinor,spentAmountMinor:calc.spentAmountMinor,remainingAmountMinor:calc.remainingAmountMinor,isOverBudget:calc.isOverBudget,currency:row.currency,archivedAt:row.archivedAt,version:row.version};}
export async function listBudgetsByHousehold(household:string,month:string,includeArchived=false){const conditions=[eq(budgets.householdId,household),eq(budgets.month,`${month}-01`)];if(!includeArchived)conditions.push(isNull(budgets.archivedAt));const rows=await getDb().select({budget:budgets,categoryName:categories.name}).from(budgets).innerJoin(categories,and(eq(categories.id,budgets.categoryId),eq(categories.householdId,household))).where(and(...conditions)).orderBy(asc(categories.name));return Promise.all(rows.map(r=>mapRow(r.budget,r.categoryName)));}
export async function createBudgetInDb(household:string,input:{categoryId:string;month:string;limitAmountMinor:bigint;currency:string}){const [category]=await getDb().select().from(categories).where(and(eq(categories.id,input.categoryId),eq(categories.householdId,household),isNull(categories.archivedAt))).limit(1);if(!category)throw new BudgetNotFoundError("Category not found");if(category.applicability !== "expense" && category.applicability !== "both")throw new BudgetNotFoundError("Budget category must support expenses");if(typeof input.limitAmountMinor !== "bigint")throw new TypeError("Budget limit must be a bigint");const domain=createBudget({householdId:householdId(household),categoryId:categoryId(input.categoryId),month:input.month,limit:money(input.limitAmountMinor,input.currency)});const [row]=await getDb().insert(budgets).values({id:domain.id,householdId:household,categoryId:input.categoryId,month:`${input.month}-01`,limitAmountMinor:input.limitAmountMinor,currency:input.currency}).returning();if(!row)throw new Error("Budget insert failed");return mapRow(row,category.name);}
export async function updateBudgetInDb(household:string,id:string,version:number,input:{month?:string;limitAmountMinor?:bigint}){const [current]=await getDb().select({budget:budgets,categoryName:categories.name}).from(budgets).innerJoin(categories,and(eq(categories.id,budgets.categoryId),eq(categories.householdId,household))).where(and(eq(budgets.householdId,household),eq(budgets.id,id))).limit(1);if(!current)throw new BudgetNotFoundError();const [row]=await getDb().update(budgets).set({month:input.month?`${input.month}-01`:current.budget.month,limitAmountMinor:input.limitAmountMinor??current.budget.limitAmountMinor,version:sql`${budgets.version} + 1`,updatedAt:new Date()}).where(and(eq(budgets.householdId,household),eq(budgets.id,id),eq(budgets.version,version),isNull(budgets.archivedAt))).returning();if(!row)throw new BudgetConflictError();return mapRow(row,current.categoryName);}
export async function archiveBudgetInDb(household:string,id:string,version:number){const result=await getDb().update(budgets).set({archivedAt:new Date(),version:sql`${budgets.version} + 1`,updatedAt:new Date()}).where(and(eq(budgets.householdId,household),eq(budgets.id,id),eq(budgets.version,version),isNull(budgets.archivedAt)));if(result.rowCount!==1)throw new BudgetConflictError("Budget was modified or already archived");}
